#!/usr/bin/env python3
"""
External Service Configuration Script
Automatically configures Twilio, Postmark, and other external services for the comprehensive platform.
"""
import os
import requests
import json
from typing import Dict, Any

def test_twilio_credentials(account_sid: str, auth_token: str) -> Dict[str, Any]:
    """Test Twilio credentials and get account info"""
    try:
        from twilio.rest import Client
        client = Client(account_sid, auth_token)
        account = client.api.accounts(account_sid).fetch()
        
        phone_numbers = client.incoming_phone_numbers.list()
        whatsapp_numbers = [num for num in phone_numbers if 'whatsapp' in num.capabilities]
        
        return {
            "status": "success",
            "account_name": account.friendly_name,
            "account_status": account.status,
            "whatsapp_numbers": [num.phone_number for num in whatsapp_numbers]
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def test_postmark_credentials(server_token: str) -> Dict[str, Any]:
    """Test Postmark credentials and get server info"""
    try:
        headers = {
            "Accept": "application/json",
            "X-Postmark-Server-Token": server_token
        }
        response = requests.get("https://api.postmarkapp.com/server", headers=headers)
        
        if response.status_code == 200:
            server_info = response.json()
            return {
                "status": "success",
                "server_name": server_info.get("Name"),
                "server_id": server_info.get("ID"),
                "bounce_hook_url": server_info.get("BounceHookUrl"),
                "inbound_hook_url": server_info.get("InboundHookUrl")
            }
        else:
            return {"status": "error", "message": f"HTTP {response.status_code}: {response.text}"}
    except Exception as e:
        return {"status": "error", "message": str(e)}

def test_openai_credentials(api_key: str) -> Dict[str, Any]:
    """Test OpenAI credentials"""
    try:
        import openai
        openai.api_key = api_key
        
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": "Test"}],
            max_tokens=5
        )
        
        return {
            "status": "success",
            "model": response.model,
            "usage": response.usage
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def update_env_file(credentials: Dict[str, str]):
    """Update .env file with real credentials"""
    env_path = "/home/ubuntu/ecomrocket-server/.env"
    
    env_vars = {}
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                if '=' in line and not line.strip().startswith('#'):
                    key, value = line.strip().split('=', 1)
                    env_vars[key] = value
    
    env_vars.update(credentials)
    
    with open(env_path, 'w') as f:
        f.write("# External service credentials - DO NOT commit to version control\n")
        f.write("# Generated by configure_external_services.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print(f"Updated .env file with {len(credentials)} new credentials")

def main():
    """Main configuration function"""
    print("🔧 External Service Configuration Tool")
    print("=" * 50)
    
    credentials = {}
    
    print("\n📱 Twilio Configuration")
    twilio_sid = input("Enter Twilio Account SID: ").strip()
    twilio_token = input("Enter Twilio Auth Token: ").strip()
    whatsapp_number = input("Enter WhatsApp Business Number (e.g., +14155238886): ").strip()
    
    if twilio_sid and twilio_token:
        print("Testing Twilio credentials...")
        twilio_result = test_twilio_credentials(twilio_sid, twilio_token)
        if twilio_result["status"] == "success":
            print("✅ Twilio credentials valid!")
            print(f"   Account: {twilio_result['account_name']}")
            print(f"   Status: {twilio_result['account_status']}")
            credentials.update({
                "TWILIO_SID": twilio_sid,
                "TWILIO_AUTH_TOKEN": twilio_token,
                "WHATSAPP_NUMBER": whatsapp_number or "+14155238886"
            })
        else:
            print(f"❌ Twilio error: {twilio_result['message']}")
    
    print("\n📧 Postmark Configuration")
    postmark_token = input("Enter Postmark Server Token: ").strip()
    
    if postmark_token:
        print("Testing Postmark credentials...")
        postmark_result = test_postmark_credentials(postmark_token)
        if postmark_result["status"] == "success":
            print("✅ Postmark credentials valid!")
            print(f"   Server: {postmark_result['server_name']}")
            credentials["POSTMARK_SERVER_TOKEN"] = postmark_token
        else:
            print(f"❌ Postmark error: {postmark_result['message']}")
    
    print("\n🤖 OpenAI Configuration")
    openai_key = input("Enter OpenAI API Key: ").strip()
    
    if openai_key:
        print("Testing OpenAI credentials...")
        openai_result = test_openai_credentials(openai_key)
        if openai_result["status"] == "success":
            print("✅ OpenAI credentials valid!")
            credentials["OPENAI_API_KEY"] = openai_key
        else:
            print(f"❌ OpenAI error: {openai_result['message']}")
    
    if credentials:
        update_env_file(credentials)
        print(f"\n✅ Configuration complete! Updated {len(credentials)} credentials.")
        print("\n🚀 Next steps:")
        print("1. Restart the FastAPI server to load new credentials")
        print("2. Run: python test_new_features.py")
        print("3. Test WhatsApp and email functionality")
    else:
        print("\n⚠️  No valid credentials provided. Please run again with valid tokens.")

if __name__ == "__main__":
    main()
